version: "3.8"

services:
  backend:
    image: resource-scheduler-backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    image: resource-scheduler-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scheduler_db
    ports:
      - "5432:5432"
